# vim:fileencoding=utf-8:foldmethod=marker
#
# ---------------------------------------------------------
# CORE SETUP
# ---------------------------------------------------------
shell /usr/bin/fish --login
editor nvim
# Set kitty_mod as master modifer for kitty shortcuts
kitty_mod ctrl+shift

# ---------------------------------------------------------
# TEXT & APPERANCE 
# ---------------------------------------------------------
# Copy and Paste
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard

# Font Size Control
map kitty_mod+equal change_font_size all +1.0
map kitty_mod+minus change_font_size all -1.0
map kitty_mod+0 	change_font_size all 0

# Dynamic Transparency
dynamic_background_opacity yes
map kitty_mod+9            set_background_opacity +0.05
map kitty_mod+8            set_background_opacity -0.05
map kitty_mod+backspace    set_background_opacity default

# Ascetic Look (optional but recommended for clean setups)
# hide_window_decorations yes
window_padding_width 4


# ---------------------------------------------------------
# MULTIPLEXING
# ---------------------------------------------------------
# Allow window splitting natively in kitty
enabled_layouts splits, stack

# Open new split in current directory
map kitty_mod+enter launch --cwd=current --location=vsplit

# Directonal splits
map kitty_mod+down launch --cwd=current --location=hsplit
map kitty_mod+up    launch --cwd=current --location=hsplit

# Navigate between panes (vim-style)
map kitty_mod+h neighboring_window left
map kitty_mod+l neighboring_window right
map kitty_mod+k neighboring_window up
map kitty_mod+j neighboring_window down

# Tab Management
map kitty_mod+t new_tab
map kitty_mod+w close_window
map kitty_mod+] next_tab
map kitty_mod+[ previous_tab


# ---------------------------------------------------------
# DEFAULT
# ---------------------------------------------------------
background_opacity      0.85
initial_window_width     1300
initial_window_height    800
remember_window_size    no


# ---------------------------------------------------------
# FONT
# ---------------------------------------------------------
font_family         JetBrainsMono Nerd Font Mono
bold_font           JetBrainsMono Nerd Mono Extra Bold
bold_italic_font    JetBraonsMono Nerd Mono Extra Bold Italic

# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME
